# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/monthly_budget_tracker
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=Ym9sZXRyYWNrZXJzZWNyZXRrZXltdXN0YmVsb25ndWZuam9rZW4=
app.jwt.expiration=86400000

# CORS
app.cors.allowed-origins=http://localhost:5173

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.default-property-inclusion=non_null
